AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/**
    - config/**
    - script/**
    - bin/**
    - features/support/env.rb

LineLength:
  Max: 80 

Documentation:
  Enabled: false
